DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/ClassbasedViews/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^cbv/',views.CBV.as_view(),name='basicCBVPage'),
    url(r'^templateView/',views.TBV.as_view(),name='TemplateViewCBVPage'),
    url(r'^app/',include('app.urls',namespace='app')),
]

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/urls.py
from django.conf.urls import url
from app.views import CBV,TBV,SchoolListView,SchoolDetailView,SchoolCreateView


app_name = 'app'

urlpatterns = [
url(r'^cbv/$',CBV.as_view(),name='ViewBasedPage'),
url(r'^tbv/$',TBV.as_view(),name='TemplateBasedViewPage'),
url(r'^listview/$',SchoolListView.as_view(),name='ListViewPage'),
url(r'^detailview/<pk>$',SchoolDetailView.as_view(),name='DetailViewPage'),
url(r'^school/(?P<pk>[-\w]+)$',SchoolDetailView.as_view(),name='Detail'),
url(r'^create/',SchoolCreateView.as_view(),name='createSchool'),
]

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=264)
    principal = models.CharField(max_length=255)
    location = models.CharField(max_length=300)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('app:Detail',kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=264)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='studentOf')

    def __str__(self):
        return self.name

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from app.models import School,Student
# Create your views here.
def index(req):
    return render(req,'app/index.html',{'title':'Advanced Topic','heading':'Welcome to Advanced Sections of Django','isLinkActive':'','paragraph':'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'})

class CBV(View):
    def get(self,request):
        return render(request,'app/index.html',{'title':'Class Based View','heading':'Class Based View - View','isLinkActive':'active','paragraph':'This page is Generated using Simplest Class based View - "View". '})

class TBV(TemplateView):
    template_name = 'app/index.html'

    def get_context_data(self,**kwargs):
        contex_var = super().get_context_data(**kwargs)
        contex_var['heading'] = 'Template Based View Page'
        contex_var['paragraph'] = 'This Page is generated by TemplateBasedView'
        contex_var['title'] = 'Template View usage'
        return contex_var

class SchoolListView(ListView):
    # generally returns the context_object_name as model lower case name and adds underscore _list
    context_object_name = 'schools'
    model = School
    template_name = 'app/school_list.html'

    def get_context_data(self,**kwargs):
        context_var = super(SchoolListView,self).get_context_data(**kwargs)
        context_var['title'] = 'List View Example Page'
        return context_var


class SchoolDetailView(DetailView):
    # genrally returns the context_object_name as model ka lowercase name
    context_object_name = 'school_detail'
    model = School
    template_name = 'app/school_detail.html'

    def get_context_data(self,**kwargs):
        context_var = super(SchoolDetailView,self).get_context_data(**kwargs)
        context_var['title'] = 'List View Example Page'
        return context_var

class SchoolCreateView(CreateView):

    model = School
    fields = ('name','location','principal')
    def get_context_data(self,**kwargs):
        context_var = super(SchoolCreateView,self).get_context_data(**kwargs)
        context_var['title'] = 'Create View Example Page'
        return context_var

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/templates/app/app_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ titleOfPage}}</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/custom_css_index.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Advanced Django Topics</a>
          <!-- different brand name compared to one at templates/app/base.html just to know which one is refererred when -->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="navbar-link {{ isLinkActive }}"><a href="cbv">Simplest CB View <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'app:TemplateBasedViewPage' %}" class="navbar-link">TemplateBasedView</a></li>
            <li><a href="{% url 'app:ListViewPage' %}" class="navbar-link">ListViewPage</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">AdminPage</a></li>

          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </div>
  </nav>
  {% block body_block %}
  {% endblock %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/templates/app/school_detail.html
{% extends 'app/app_base.html' %}
{% block body_block %}
<div class="container">
  <div class="well">

      <div class="panel panel-success">
        <div class="panel-heading">{{school_detail.name}}</div>
        <div class="panel-body">
          Location : {{school_detail.location}}<br />
          Principal : {{school_detail.principal}}
        </div>
      </div>

</div>
<div class="well-lg">
  <ul class="list-group">
      {% for student in school_detail.studentOf.all %}
  <li class="list-group-item">
    <span class="badge">Age: {{student.age}}</span>
    {{student.name}}
  </li>
    {% endfor %}
</ul>



</div>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/app/templates/app/school_list.html
{% extends 'app/app_base.html' %}
{% block body_block %}
<div class="container">
  <ol class="list-group">
    {% for school in schools %}
    <li class="list-group-item">

      <div class="panel panel-default">
        <div class="panel-heading">{{school.name}}</div>
        <div class="panel-body">
          Location : {{school.location}}
          <br />
          <a href="/app/school/{{school.id}}" class="btn btn-primary">More Details</a>
        </div>
      </div>
      <a href="{% url 'app:ListViewPage' %}"></a>

    </li>
    {% endfor %}
  </ol>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/templates/app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ titleOfPage}}</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/custom_css_index.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Django Advanced Topics</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="navbar-link {{ isLinkActive }}"><a href="./cbv/">Simplest CB View <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'app:TemplateBasedViewPage' %}" class="navbar-link">TemplateBasedView</a></li>
            <li><a href="{% url 'app:ListViewPage' %}" class="navbar-link">ListView</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>

          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </div>
  </nav>
  {% block body_block %}
  {% endblock %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/templates/app/cbv.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="container-fluid">
  <div class="jumbotron">
    <div class="container">
      <h1>{{ heading }}</h1>
      <p>{{ paragraph }}</p>
    </div>
  </div>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/templates/app/index.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="container-fluid">
  <div class="jumbotron">
    <div class="container">
      <h1>{{ heading }}</h1>
      <p>{{ paragraph }}</p>
    </div>
  </div>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/AdvancedTopics/ClassbasedViews/templates/app/school_form.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="container-fluid">
  <div class="jumbotron">
    <div class="container">
      <h1> Create View</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    </div>
  </div>
  <div class="well">
    <h1>
      {% if not form.instance.pk %}
      Create Form
      {% else %}
      Update School
      {% endif %}
    </h1>
    <hr />
    <form class="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" name="button" class="btn btn-success">Submit</button>
    </form>
  </div>
</div>
{% endblock %}