DjangoFullStackDeveloperCourse/RevisitingTemplates/RevisitingTemplates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^app/',include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

DjangoFullStackDeveloperCourse/RevisitingTemplates/app/urls.py
from django.conf.urls import url
from app import views

#Templates_namespace
app_name = 'app'

# urlpatterns = [
# url(r'other/',views.other,name="otherKaPage"),
# url(r'relative_url_templates/',views.relative_url_templates,name="relative_url_templatesKaPage"),
# url(r'$',views.index,name="indexKaPage"),
# ]

urlpatterns = [
url(r'^other/$',views.other,name="otherKaPage"),
url(r'^relative/$',views.relative_url_templates,name="relativeKaPage"),
url(r'^filter/$',views.filterPage,name="filterKaPage")
]

DjangoFullStackDeveloperCourse/RevisitingTemplates/app/models.py
from django.db import models

# Create your models here.

DjangoFullStackDeveloperCourse/RevisitingTemplates/app/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req,'app/index.html',{'title':'Welcome Page'})

def other(req):
    return render(req,'app/other.html',{'title':'Other ka Page'})

def relative_url_templates(req):
    return render(req,'app/relative_url_templates.html',{'title':'Relative Ka Paege'})

def filterPage(req):
    import datetime
    contextVar = {'heading':"the heading text",'p':datetime.datetime.now(),'someNumber':123456}
    return render(req,'app/filter.html',context=contextVar)

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
            <li class="navbar-brand"><a href="{% url 'index' %}">Templates</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin-Page</a></li>

            <li><a href="{% url 'app:otherKaPage' %}" class="navbar-link">Other-Page</a></li>
            <li><a href="{% url 'app:relativeKaPage' %}" class="navbar-link">Relative-Page</a></li>
            <li><a href="{% url 'app:filterKaPage' %}" class="navbar-link">Filter-Page</a></li>
        </ul>
      </div>

    </nav>
    <div class="container-fluid">

      {% block body_block %}
      {% endblock %}

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/filter.html
{% extends 'app/base.html' %}
{% block body_block %}
{% load my_custom_tags %}
<div class="jumbotron">
  <h1>{{ heading | cutV2:'text' }}</h1>
  <p> This is example of template inheritance. Today is {{p}} </p>
  <p>{{ someNumber | add:10101 }}</p>
  <p>Individual Words that makeup the heading are {{ heading | splitItBy:' ' }} </p>
  <a href="{% url 'index' %}" class="btn btn-default">IndexPage</a>
  <a href="{% url 'admin:index' %}" class="btn btn-default">AdminIndex</a>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/index.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to Index</h1>
  <p> This app explores more into templates, such as Relative URLS, ways a URL can be referred, better and future-proof practice, Template Inheritance etc.</p>

  <a href="{% url 'app:otherKaPage' %}" class="btn btn-default">Other</a>
  <a href="{% url 'app:relativeKaPage' %}" class="btn btn-default">Relative</a>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/other.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Other</h1>
  <p> This is example of template inheritance.</p>
  <a href="{% url 'index' %}" class="btn btn-default">IndexPage</a>
  <a href="{% url 'admin:index' %}" class="btn btn-default">AdminIndex</a>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/other0.html
{% extends 'app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Other</h1>
  <p> This is example of template inheritance.</p>
  <a href="{% url 'index' %}" class="btn btn-default">IndexPage</a>
  <a href="{% url 'admin:index' %}" class="btn btn-default">AdminIndex</a>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/RevisitingTemplates/templates/app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Deep Dive into Templates | RELATIVE URL TEMPLATES </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Relative URL TEMPLATES </h1>
        <p> This app explores more into templates, such as Relative URLS, ways a URL can be referred, better and future-proof practice, Template Inheritance etc.</p>
        <a href="{% url 'index' %}" class="btn btn-default">IndexPage</a>
        <a href="{% url 'admin:index' %}" class="btn btn-default">AdminIndex</a> 
      </div>
    </div
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>