DjangoFullStackDeveloperCourse/LearningUserAuthentication/LearningUserAuthentication/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from init_app import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('init_app.urls')),
    url(r'^spcl/',views.special,name='specialURL'),
]

DjangoFullStackDeveloperCourse/LearningUserAuthentication/init_app/urls.py
from django.conf.urls import url
from init_app import views


app_name = 'init_app'

urlpatterns = [
url(r'^register/',views.registeredMethod,name='registerURL'),
]

DjangoFullStackDeveloperCourse/LearningUserAuthentication/init_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portfolio_link = models.URLField(blank=True)

    profile_image = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

DjangoFullStackDeveloperCourse/LearningUserAuthentication/init_app/forms.py
from django import forms
from django.contrib.auth.models import User
from init_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_link','profile_image')

DjangoFullStackDeveloperCourse/LearningUserAuthentication/init_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from init_app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(req):
    return render(req,'init_app/index.html')
@login_required
def special(req):
    return HttpResponse('You are logged in')

def registeredMethod(req):
    registered = False

    if req.method == 'POST':
        user_form = UserForm(data = req.POST)
        profile_form = UserProfileInfoForm(data = req.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_image' in req.FILES:
                profile.profile_image = req.FILES['profile_image']
            profile.save()

            registered = True
        else:
            print("Not a POST Request")
            print(profile_form.errors,user_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(req,'init_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

DjangoFullStackDeveloperCourse/LearningUserAuthentication/templates/init_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
            <li class="navbar-brand"><a href="{% url 'index' %}">Django-home</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin-Page</a></li>

            <li><a href="#" class="navbar-link">Login</a></li>
            <li><a href="{% url 'init_app:registerURL' %}" class="navbar-link">Register</a></li>
        </ul>
      </div>

    </nav>
    <div class="container-fluid">

      {% block body_block %}
      {% endblock %}

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

DjangoFullStackDeveloperCourse/LearningUserAuthentication/templates/init_app/index.html
{% extends 'init_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome Page</h1>
</div>
{% endblock %}

DjangoFullStackDeveloperCourse/LearningUserAuthentication/templates/init_app/registration.html
{% extends 'init_app/base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
  <h1>Registration Page</h1>
  {% if registered %}
  <p>Thanks for Registration</p>
  {% else %}
  <p>Register here Ma'am / Sir </p>
  <form enctype="multipart/form-data" class="" action="index.html" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{profile_form.as_p}}
    <button type="submit" name="button">Register</button>
  </form>
  {% endif %}
</div>
{% endblock %}